### PR TITLE
Fix compilation for MXE on Linux and WSL

### PR DESCRIPTION
**Pull request by coltongit**
Even though this isn't usually an option on the wiki, this will allow for cross-compilation of sm64pc through MXE on both Linux and WSL, making Wine testing much easier.

### CODE REVIEW

**Comment by MissLav** [comment]
helll yeah no more need for a windows vm to compile for windows

**Comment by coltongit** [comment]
Has anyone attempted to test sm64pc on Wine?

**Comment by dgeneratioN** [comment]
Don't want to flood you with mxe problems, but I can't compile for windows on WSL.
```
build/us_pc/src/game/envfx_snow.o: In function `envfx_init_snow':
/mnt/e/dev/sm64pc/src/game/envfx_snow.c:87: undefined reference to `bzero'
build/us_pc/src/game/envfx_bubbles.o: In function `envfx_init_bubble':
/mnt/e/dev/sm64pc/src/game/envfx_bubbles.c:355: undefined reference to `bzero'
/mnt/e/dev/sm64pc/src/game/envfx_bubbles.c:356: undefined reference to `bzero'
build/us_pc/src/game/save_file.o: In function `write_eeprom_savefile':
/mnt/e/dev/sm64pc/src/game/save_file.c:160: undefined reference to `bcopy'
build/us_pc/src/game/save_file.o: In function `write_eeprom_menudata':
/mnt/e/dev/sm64pc/src/game/save_file.c:175: undefined reference to `bcopy'
build/us_pc/src/game/save_file.o: In function `restore_main_menu_data':
/mnt/e/dev/sm64pc/src/game/save_file.c:230: undefined reference to `bcopy'
build/us_pc/src/game/save_file.o: In function `wipe_main_menu_data':
/mnt/e/dev/sm64pc/src/game/save_file.c:252: undefined reference to `bzero'
build/us_pc/src/game/save_file.o: In function `restore_save_file_data':
/mnt/e/dev/sm64pc/src/game/save_file.c:317: undefined reference to `bcopy'
build/us_pc/src/game/save_file.o: In function `save_file_do_save':
/mnt/e/dev/sm64pc/src/game/save_file.c:359: undefined reference to `bcopy'
build/us_pc/src/game/save_file.o: In function `save_file_erase':
/mnt/e/dev/sm64pc/src/game/save_file.c:373: undefined reference to `bzero'
build/us_pc/src/game/save_file.o: In function `save_file_copy':
/mnt/e/dev/sm64pc/src/game/save_file.c:384: undefined reference to `bcopy'
build/us_pc/src/game/save_file.o: In function `save_file_load_all':
/mnt/e/dev/sm64pc/src/game/save_file.c:398: undefined reference to `bzero'
build/us_pc/src/game/save_file.o: In function `save_file_reload':
/mnt/e/dev/sm64pc/src/game/save_file.c:446: undefined reference to `bcopy'
build/us_pc/src/pc/controller/controller_keyboard.o: In function `keyboard_bindkeys':/mnt/e/dev/sm64pc/src/pc/controller/controller_keyboard.c:61: undefined reference to
`bzero'
build/us_pc/src/pc/controller/controller_sdl.o: In function `controller_sdl_bind':
/mnt/e/dev/sm64pc/src/pc/controller/controller_sdl.c:66: undefined reference to `bzero'
/mnt/e/dev/sm64pc/src/pc/controller/controller_sdl.c:67: undefined reference to `bzero'
```

I tried to build with: `make WINDOWS_BUILD=1 CROSS=i686-w64-mingw32.static-
-j6`

**Comment by dgeneratioN** [comment]
> I've tried to build with: `make WINDOWS_BUILD=1 CROSS=i686-w64-mingw32.static- -j6`

oops my mistake, accidentally switched to master branch, its all working on nightly

**Comment by coltongit** [comment]
It's OK. Nightly has it all working anyway. For master use NO_BZERO_BCOPY=1 when you compile. Nightly has that built-in

**Pull request merged**
