### PR TITLE
Fix macOS builds being broken

### LINKED ISSUE #462: vsnprintf delcaration issue on Big Sur?
Hey everyone.  Bear with me as this stuff is not my forte.  I just came across some tutorials to install sm64 on a MAC and i'm running into the below issue, which lead me here.  I'm kind of stuck.  I read other issues and tried some suggestions, but nothing appears to work.  Any help would be appreciated.  Cheers!

```
gcc -Llib -Iinclude -I../include -I . -Wall -Wextra -Wno-unused-parameter -DOSX_BUILD -pedantic -std=c99 -O2 -s -DOSX_BUILD aiff_extract_codebook.c -lm -o aiff_extract_codebook 
aiff_extract_codebook.c:48:16: error: implicitly declaring library function 'vsnprintf' with type 'int (char *, unsigned long, const char *, struct __va_list_tag *)'
      [-Werror,-Wimplicit-function-declaration]
    int size = vsnprintf(NULL, 0, fmt, ap);
               ^
aiff_extract_codebook.c:48:16: note: include the header <stdio.h> or explicitly provide a declaration for 'vsnprintf'
1 error generated.
```

### PR DESCRIPTION
**Pull request by Xenthio**
checked on macOS 12 on Apple M1 Arm, should work on everything else too. (USING GCC 11)
fixes issues laid out in #83 and closes #462 and #447

### CODE REVIEW

**Comment by fgsfdsfgs** [comment]
Please see my comment in #83. Try applying `-std=gnu99` for that particular tool. No need to enable `-Wno-error=implicit-function-declaration`.

**Comment by Xenthio** [comment]
> Please see my comment in #83. Try applying `-std=gnu99` for that particular tool. No need to enable `-Wno-error=implicit-function-declaration`.

pretty sure i checked and that was already there, lemme look again

**Comment by fgsfdsfgs** [comment]
Also to properly ignore all DS_Store files it should be enough to just add `.DS_Store` to gitignore.

**Comment by Xenthio** [comment]
> Also to properly ignore all DS_Store files it should be enough to just add `.DS_Store` to gitignore.

pretty sure that only ignored them in the root dir, but I could be remembering incorrectly.

**Comment by fgsfdsfgs** [comment]
Nah, when you don't prefix it with a `/` it applies to the entire directory tree. Unless there's a `/` in the middle of the path already.

**Comment by Xenthio** [comment]
this should also fix #462

**Pull request merged**
