### PR TITLE
Haiku port oneliner

### PR DESCRIPTION
**Pull request by mmuman**
We provide bcopy/bzero macros like macOS.

### CODE REVIEW

**Comment by fgsfdsfgs** [comment]
Try retargeting this into the `nightly` branch. I should really make that the main one.

**Comment by mmuman** [comment]
Ah yes that'd be a nice hint. Let's see that.

**Comment by mmuman** [comment]
And… of course it won't be that easy, "can't find -ldl" :-D

**Comment by fgsfdsfgs** [comment]
It's only really used in the Discord RPC component which requires a shared lib, you can just disable that with a build flag.

**Comment by mmuman** [comment]
I guess we can close this one.

**Pull request closed without merging**
