### PR TITLE
Making this code MinGW.org (not mingw-w64) and MSYS1 compatible

### PR DESCRIPTION
**Pull request by yksoft1**
Is there only me who's still using MinGW.org and MSYS1? I know it has lots of quirks and dirty hacks, however I'm using this toolchain for more than 12 years and got great affection for it.

msys1

Prerequisites for building sm64pc using MinGW.org (GCC 5.1 and later) and MSYS1:
1. Install Python 3.7 or higher in Windows. Make sure that Python path in %PATH% when running MSYS1, and python.exe copied to python3.exe.
2. Build and install libogg, libflac, libSDL2, libglew and libaudiofile-0.3.6 in your environment.
3. Get a newer make.exe for MSYS1. The original MSYS1 one won't work with sm64pc's Makefile.
I got a working one from the "msys+7za+wget+svn+git+mercurial+cvs-rev13" package.
4. Get a working util-linux hexdump, which MSYS1 lacks, and its dependencies.  The one from GnuWin32 (http://gnuwin32.sourceforge.net/packages/util-linux-ng.htm) is very old but still does its job.

Please test this patch to see if it breaks building on mingw-w64 and other platforms.

### CODE REVIEW

**Comment by fgsfdsfgs** [comment]
Wow. I didn't even know this could be built with GCC6 correctly.

**Comment by yksoft1** [comment]
> Wow. I didn't even know this could be built with GCC6 correctly.

I've tried this as low as GCC 4.8.1, but it could only produce a working binary at least on 5.1, with flag -no-pie removed.

**Comment by coltongit** [comment]
I got it to almost build once on MXE in Linux but make complained about not having the right emulation type. Perhaps a newer ld is needed?

**Comment by coltongit** [comment]
@yksoft1 Please send these fixes to nightly. Nightly's where all the fixes are supposed to go.

**Comment by yksoft1** [comment]
> @yksoft1 Please send these fixes to nightly. Nightly's where all the fixes are supposed to go.

I don't know if I have pull rights to this repository at all.

**Comment by coltongit** [comment]
I don't think you do, but I can get these fixes ported to nightly for you if you like

**Comment by yksoft1** [comment]
> I don't think you do, but I can get these fixes ported to nightly for you if you like

Please merge it to nightly if you think this patch is OK now.

**Comment by yksoft1** [comment]
> I don't think you do, but I can get these fixes ported to nightly for you if you like

Please merge it to nightly if you think this patch is OK now.

**Comment by coltongit** [comment]
Will do.

**Comment by coltongit** [comment]
plz rebase @yksoft1

**Comment by yksoft1** [comment]
The include guard of include/types.h may conflict with <sys/types.h> on some systems, including MinGW.org.
`
#ifndef _TYPES_H_
#define _TYPES_H_
`
I replaced them with
`
#ifndef _SM64_TYPES_H_
#define _SM64_TYPES_H_
`

**Comment by coltongit** [comment]
The fixes have been merged @yksoft1

**Comment by coltongit** [comment]
@yksoft1 Where exactly do you get that "msys+7za+wget+svn+git+mercurial+cvs-rev13" package you specified was needed to compile sm64pc under MSYS1?

**Comment by yksoft1** [comment]
> @yksoft1 Where exactly do you get that "msys+7za+wget+svn+git+mercurial+cvs-rev13" package you specified was needed to compile sm64pc under MSYS1?

Just Google it.
https://sourceforge.net/projects/mingwbuilds/files/external-binary-packages/

**Comment by coltongit** [comment]
@yksoft1 how exactly are you able to get the shortcuts for MSYS1? I'm on Win10 and they aren't showing up on my Start Menu or the desktop

**Pull request merged**
