### PR TITLE
adding option to disable draw distance

### PR DESCRIPTION
**Pull request by wabberz**
This patch will add the option to disable the drawing distance for most objects and enemies (I may have missed some, needs more testing).

~~**This will crash some levels in the 32bit version (I think it overflows the object pool), I haven't been able to fix that yet. But so far it seems to work well in the 64bit version.**~~ Fixed thanks to fgsfds!

### CODE REVIEW

**Comment by Jan200101** [comment]
I'll look into the 32bit issues if no one else wants to.
From others I've heard that this also makes every entity active, perhaps those should be disabled until the player gets close to them

**Comment by vrmiguel** [comment]
Thanks for the contribution! We'll merge it as soon as we manage to fix the bugs these changes imply. For the time being, we could add these changes as a `.patch` in `./enhancements`, if you want to.


BTW, if you'd like to join our sm64pc Discord server, DM me at Pathétique#3159 :)

**Comment by Hyenadae** [comment]
This will 99% probably make it impossible to have a Scuttlebug Jamboree

**Comment by wabberz** [comment]
> For the time being, we could add these changes as a `.patch` in `./enhancements`, if you want to.
That's fine. It's just something I did for myself and thought others might enjoy as well, so I shared it.

I did notice that the Heave-Ho on the lowest level in Wet-Dry World bugs out (he drops into the ground), I'll see if I can fix that.

**Comment by Jan200101** [comment]
perhaps instead of a patch, that could possibly break with future revisions of the repo, a Build flag would be more appropriate

**Comment by wabberz** [comment]
It is a build flag in this PR, @vrmiguel just added it as a patch until this can be merged into master

**Comment by Jan200101** [comment]
oh my bad.
I don't see the reason for a patch then since its already an opt-in thing

**Comment by Hyenadae** [comment]
Def should make a note for the (few) users of much weaker hardware (1-2ghz CPUs with 2 or less cores) that this may decrease performance.

**Comment by Jan200101** [comment]
since this has been merged the patch can be removed

**Pull request merged**
