### PR TITLE
Press start to play fix for ex

### PR DESCRIPTION
**Pull request by tailscreatesstuff32**
I fixed the press start to play issue. Locate in level_select_menu.c

### CODE REVIEW

**Comment by fgsfdsfgs** [comment]
You seem to have tried to PR a nightly-based branch into master. Please retarget to nightly.

**Comment by coltongit** [comment]
@fgsfdsfgs Target's changed to the proper target. Try another look now

**Comment by fgsfdsfgs** [comment]
That diff nukes and replaces the entire file. Maybe different line endings? I wouldn't advise using Github's file upload feature for PRs.

**Comment by coltongit** [comment]
The one who made this PR isn't very well versed with PRs in general so I may try to optimize this PR a bit later. Hopefully it'll help

**Comment by rawr51919** [comment]
PR #455 supersedes this PR

**Comment by fgsfdsfgs** [comment]
This still nukes and replaces the entire file, so closing.

**Pull request closed without merging**
